kind: Service
apiVersion: v1
metadata:
  name: osg-frontier-squid
spec:
  type: NodePort
  selector:
    app: osg-frontier-squid
  ports:
  - port: 3128
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: osg-frontier-squid-deployment
  labels:
    app: osg-frontier-squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osg-frontier-squid
  template:
    metadata:
      labels:
        app: osg-frontier-squid
    spec:
      containers:
      - name: osg-frontier-squid
        image: slateci/osg-frontier-squid
        ports:
        - containerPort: 3128
