apiVersion: v1
#kind: Pod
#metadata:
#  name: proxy-user-deployment
#  labels:
#    app: proxy-user-deployment
#    proxy: using
#spec:
#  containers:
#  - name: proxy-user-deployment
#    image: nicolaka/netshoot
#    command: [ "/bin/sh", "-c", "--" ]
#    args: [ "while true; do sleep 30; done;" ]
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: proxy-user-deployment
  labels:
    app: proxy-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-user-deployment
  template:
    metadata:
      labels:
        app: proxy-user-deployment
        proxy: using
    spec:
      containers:
      - name: proxy-user-deployment
        image: nicolaka/netshoot
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
