# Name of the workflow
name: Build and push container images

# Events that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
      - testing-branch  # Trigger on push to the testing-branch
  pull_request:  # Trigger on pull requests
  workflow_dispatch:  # Manual trigger from GitHub UI
  repository_dispatch:
    types: [dispatch-build]  # Trigger on custom repository dispatch events of type 'dispatch-build'

# Jobs to be executed
jobs:
  make-date-tag:
    runs-on: ubuntu-latest  # Job runs on the latest version of Ubuntu
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}  # Output variable 'dtag' from the step 'mkdatetag'
    steps:
      - name: make date tag  # Name of the step
        id: mkdatetag  # ID of the step
        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT  # Command to generate a date tag and set it as output

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: image-list
        run: |
          ORG_DIR=opensciencegrid
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
             [[ $GITHUB_EVENT_NAME == 'push' ]]; then
               if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
                   BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
               elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                   BASE=${{github.event.before}}
               else
                   BASE=origin/main
               fi
               images=$(git diff --name-only \
                                 "$BASE" \
                                 "$GITHUB_SHA" |
                        egrep "^$ORG_DIR/" |
                        cut -d/ -f -2 |
                        sort |
                        uniq |
                        xargs -I {} find . -type d \
                                           -wholename ./{} \
                                           -printf "%P\n")
          else
               images=$(find $ORG_DIR -mindepth 1 \
                                      -maxdepth 1 \
                                      -type d \
                                      -printf "$ORG_DIR/%P\n")
          fi
          image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n")')
          echo "json=$image_json" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: build-image-list
    if: needs.build-image-list.outputs.images != '["dummy"]'
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
    steps:
      - name: Check for build-config.json in ${{ matrix.image }}
        id: check-jsonfile
        run: |
          if [ ! -f "${{ matrix.image }}/build-config.json" ]; then
            echo "No build-config.json found in ${{ matrix.image }}. Creating default build-config.json."
            cat <<EOF >${{ matrix.image }}/build-config.json
            {
              "base_os": {
                "base_name": "default_os",
                "base_version": "default_version"
              },
              "base_repo": "default-repo"
            }
            EOF
          else
            echo "build-config.json exists in ${{ matrix.image }}"
          fi

      - name: Read build-config.json in ${{ matrix.image }}
        id: read-jsonfile
        run: |
          config=$(cat ${{ matrix.image }}/build-config.json)
          base_name=$(echo $config | jq -r '.base_os.base_name')
          base_version=$(echo $config | jq -r '.base_os.base_version')
          base_repo=$(echo $config | jq -r '.base_repo')
          echo "Base name: $base_name"
          echo "Base version: $base_version"
          echo "Base repo: $base_repo"
          echo "base_name=$base_name" >> $GITHUB_ENV
          echo "base_version=$base_version" >> $GITHUB_ENV
          echo "base_repo=$base_repo" >> $GITHUB_ENV

      - name: Build ${{ matrix.image }}:${{ env.base_name }}-${{ env.base_repo }}
        if: steps.check-jsonfile.conclusion == 'success'
        continue-on-error: ${{ env.base_repo == 'development' }}
        uses: opensciencegrid/build-container-action@v0.6.0
        with:
          osg_series: ${{ env.base_version }}
          osg_repo: ${{ env.base_repo }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
        env:
          BASE_NAME: ${{ env.base_name }}
          BASE_VERSION: ${{ env.base_version }}
          BASE_REPO: ${{ env.base_repo }}

  push:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/main' && 
      github.event_name != 'pull_request' && 
      github.repository_owner == 'PPathu' &&
      needs.build-image-list.outputs.images != '["dummy"]'
    needs: [make-date-tag, build-image-list, build]
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
    steps:
      - name: Push to Harbor (${{ env.base_version }}-development)
        if: env.base_version != '23'
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ env.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ env.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Docker Hub (${{ env.base_version }}-development)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ env.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ env.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ env.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ env.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}