name: Main Workflow

on:
  push:
    branches:
      - main
      - testing-branch
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-build]

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
      - name: make date tag
        id: mkdatetag
        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: image-list
        run: |
          ORG_DIR=opensciencegrid
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
             [[ $GITHUB_EVENT_NAME == 'push' ]]; then
               if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
                   BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
               elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                   BASE=${{github.event.before}}
               else
                   BASE=origin/main
               fi
               images=$(git diff --name-only \
                                 "$BASE" \
                                 "$GITHUB_SHA" |
                        egrep "^$ORG_DIR/" |
                        cut -d/ -f -2 |
                        sort |
                        uniq |
                        xargs -I {} find . -type d \
                                           -wholename ./{} \
                                           -printf "%P\n")
          else
               images=$(find $ORG_DIR -mindepth 1 \
                                      -maxdepth 1 \
                                      -type d \
                                      -printf "$ORG_DIR/%P\n")
          fi
          image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n")')
          echo "json=$image_json" >> $GITHUB_OUTPUT
          
  check-config:
    runs-on: ubuntu-latest
    needs: [make-date-tag, build-image-list]
    outputs:
      standard_enabled: ${{ steps.read-config.outputs.standard_enabled }}
      repo_enabled: ${{ steps.read-config.outputs.repo_enabled }}
      base_name_standard: ${{ steps.read-config.outputs.base_name_standard }}
      base_version_standard: ${{ steps.read-config.outputs.base_version_standard }}
      base_repo_standard: ${{ steps.read-config.outputs.base_repo_standard }}
      base_name_repo: ${{ steps.read-config.outputs.base_name_repo }}
      base_version_repo: ${{ steps.read-config.outputs.base_version_repo }}
      base_repo_repo: ${{ steps.read-config.outputs.base_repo_repo }}
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for build-config.json in ${{ matrix.image }}
        id: check-jsonfile
        run: |
          if [ -f "${{ matrix.image }}/build-config.json" ]; then
            echo "build-config.json exists in ${{ matrix.image }}"
            echo "config_exists=true" >> $GITHUB_OUTPUT
          else
            echo "No build-config.json found in ${{ matrix.image }}"
            echo "config_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Read build-config.json in ${{ matrix.image }}
        id: read-config
        if: steps.check-jsonfile.outputs.config_exists == 'true'
        run: |
          config=$(cat ${{ matrix.image }}/build-config.json)
          standard_enabled=$(echo $config | jq -r '.standard_build.enabled')
          repo_enabled=$(echo $config | jq -r '.repo_build.enabled')
          base_name_standard=$(echo $config | jq -r '.standard_build.base_os.base_name | join(",")')
          base_version_standard=$(echo $config | jq -r '.standard_build.base_os.base_version | join(",")')
          base_repo_standard=$(echo $config | jq -r '.standard_build.base_repo')
          base_name_repo=$(echo $config | jq -r '.repo_build.base_os.base_name | join(",")')
          base_version_repo=$(echo $config | jq -r '.repo_build.base_os.base_version | join(",")')
          base_repo_repo=$(echo $config | jq -r '.repo_build.base_repo')
          
          echo "standard_enabled=$standard_enabled" >> $GITHUB_OUTPUT
          echo "repo_enabled=$repo_enabled" >> $GITHUB_OUTPUT
          echo "base_name_standard=$base_name_standard" >> $GITHUB_OUTPUT
          echo "base_version_standard=$base_version_standard" >> $GITHUB_OUTPUT
          echo "base_repo_standard=$base_repo_standard" >> $GITHUB_OUTPUT
          echo "base_name_repo=$base_name_repo" >> $GITHUB_OUTPUT
          echo "base_version_repo=$base_version_repo" >> $GITHUB_OUTPUT
          echo "base_repo_repo=$base_repo_repo" >> $GITHUB_OUTPUT

      - name: Set default values if build-config.json is missing
        if: steps.check-jsonfile.outputs.config_exists == 'false'
        run: |
          echo "standard_enabled=true" >> $GITHUB_OUTPUT
          echo "repo_enabled=true" >> $GITHUB_OUTPUT
          echo "base_name_standard=el9" >> $GITHUB_OUTPUT
          echo "base_version_standard=23" >> $GITHUB_OUTPUT
          echo "base_repo_standard=testing" >> $GITHUB_OUTPUT
          echo "base_name_repo=el9" >> $GITHUB_OUTPUT
          echo "base_version_repo=23" >> $GITHUB_OUTPUT
          echo "base_repo_repo=testing" >> $GITHUB_OUTPUT

  trigger-builds:
    needs: check-config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [standard, repo]
    steps:
      - name: Trigger standard build workflow
        if: ${{ matrix.config == 'standard' && (needs.check-config.outputs.standard_enabled == 'true' || needs.check-config.outputs.standard_enabled == '') }}
        uses: actions/github-script@v4
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'standard-build.yml',
              ref: context.ref,
              inputs: {
                image: "${{ matrix.image }}",
                base_name: "${{ needs.check-config.outputs.base_name_standard }}",
                base_version: "${{ needs.check-config.outputs.base_version_standard }}",
                base_repo: "${{ needs.check-config.outputs.base_repo_standard }}"
              }
            });
            console.log(result);

      - name: Trigger repo build workflow
        if: ${{ matrix.config == 'repo' && (needs.check-config.outputs.repo_enabled == 'true' || needs.check-config.outputs.repo_enabled == '') }}
        uses: actions/github-script@v4
        with:
          script: |
            const result = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'repo-build.yml',
              ref: context.ref,
              inputs: {
                image: "${{ matrix.image }}",
                base_name: "${{ needs.check-config.outputs.base_name_repo }}",
                base_version: "${{ needs.check-config.outputs.base_version_repo }}",
                base_repo: "${{ needs.check-config.outputs.base_repo_repo }}"
              }
            });
            console.log(result);
