name: Build and push container images

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-build]

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
      - name: make date tag
        id: mkdatetag
        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: image-list
        run: |
          ORG_DIR=opensciencegrid
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
             [[ $GITHUB_EVENT_NAME == 'push' ]]; then
               if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
                   BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
               elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                   BASE=${{github.event.before}}
               else
                   BASE=origin/main
               fi
               images=$(git diff --name-only \
                                 "$BASE" \
                                 "$GITHUB_SHA" |
                        egrep "^$ORG_DIR/" |
                        cut -d/ -f -2 |
                        sort |
                        uniq |
                        xargs -I {} find . -type d \
                                           -wholename ./{} \
                                           -printf "%P\n")
          else
               images=$(find $ORG_DIR -mindepth 1 \
                                      -maxdepth 1 \
                                      -type d \
                                      -printf "$ORG_DIR/%P\n")
          fi

          image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n")')
          echo "json=$image_json" >> $GITHUB_OUTPUT

  generate-matrix:
    runs-on: ubuntu-latest
    needs: build-image-list
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate build matrix
        id: generate-matrix
        run: |
          CONFIG_FILE="${{ matrix.image }}/build-config.json"
          if [[ -f "$CONFIG_FILE" ]]; then
            base_os=$(jq -r '.base_os.base_name[]' $CONFIG_FILE | jq -Rs 'split("\n")[:-1]')
            base_version=$(jq -r '.base_os.base_version[]' $CONFIG_FILE | jq -Rs 'split("\n")[:-1]')
            base_repo=$(jq -r '.base_repo' $CONFIG_FILE)
          else
            base_os='["el7"]'
            base_version='["3.6"]'
            base_repo="testing"
          fi
          matrix=$(jq -n \
            --argjson base_os "$base_os" \
            --argjson base_version "$base_version" \
            --arg base_repo "$base_repo" \
            '{
              "include": $base_os | map({"base_os": ., "base_version": $base_version[], "base_repo": $base_repo}) | add'
            )
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [build-image-list, generate-matrix]
    if: needs.build-image-list.outputs.images != '["dummy"]'
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.generate-matrix.outputs.matrix).include }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build ${{ matrix.config.base_os }}:${{ matrix.config.base_version }}-${{ matrix.config.base_repo }}
        continue-on-error: false
        uses: opensciencegrid/build-container-action@v0.6.0
        with:
          osg_series: ${{ matrix.config.base_version }}
          osg_repo: ${{ matrix.config.base_repo }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}

  push:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/main' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'opensciencegrid' &&
      needs.build-image-list.outputs.images != '["dummy"]'
    needs: [make-date-tag, build-image-list, build]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.generate-matrix.outputs.matrix).include }}
    steps:
      - name: Push to Harbor (${matrix.config.base_version}-${matrix.config.base_repo})
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: ${{ matrix.config.base_repo }}
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Docker Hub (${matrix.config.base_version}-${matrix.config.base_repo})
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: ${{ matrix.config.base_repo }}
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Harbor (${{ matrix.config.base_version }}-development)
        if: ${{ matrix.config.base_version != '23' }}
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ matrix.config.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ matrix.config.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Docker Hub (${{ matrix.config.base_version }}-development)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ matrix.config.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ matrix.config.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ matrix.config.base_version }}
          context: ${{ matrix.image }}
          base_os: ${{ matrix.config.base_os }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}