name: Main Workflow

on:
  push:
    branches:
      - main
      - testing-branch
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-build]

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
      - name: make date tag
        id: mkdatetag
        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: image-list
        run: |
          ORG_DIR=opensciencegrid
          if [[ $GITHUB_EVENT_NAME == 'pull_request' ]] ||
             [[ $GITHUB_EVENT_NAME == 'push' ]]; then
               if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
                   BASE=$(git merge-base origin/$GITHUB_BASE_REF HEAD)
               elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
                   BASE=${{github.event.before}}
               else
                   BASE=origin/main
               fi
               images=$(git diff --name-only \
                                 "$BASE" \
                                 "$GITHUB_SHA" |
                        egrep "^$ORG_DIR/" |
                        cut -d/ -f -2 |
                        sort |
                        uniq |
                        xargs -I {} find . -type d \
                                           -wholename ./{} \
                                           -printf "%P\n")
          else
               images=$(find $ORG_DIR -mindepth 1 \
                                      -maxdepth 1 \
                                      -type d \
                                      -printf "$ORG_DIR/%P\n")
          fi
          image_json=$(echo -n "${images:-dummy}" | jq -Rcs '.|split("\n")')
          echo "json=$image_json" >> $GITHUB_OUTPUT

  check-config:
    runs-on: ubuntu-latest
    needs: [make-date-tag, build-image-list]
    outputs:
      image_combinations: ${{ steps.combine-config.outputs.image_combinations }}
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.build-image-list.outputs.images) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for build-config.json in ${{ matrix.image }}
        id: check-jsonfile
        run: |
          if [ -f "${{ matrix.image }}/build-config.json" ]; then
            echo "build-config.json exists in ${{ matrix.image }}"
            echo "config_exists=true" >> $GITHUB_OUTPUT
          else
            echo "No build-config.json found in ${{ matrix.image }}"
            echo "config_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Read build-config.json in ${{ matrix.image }}
        id: read-config
        if: steps.check-jsonfile.outputs.config_exists == 'true'
        run: |
          config=$(cat ${{ matrix.image }}/build-config.json)
          standard_enabled=$(echo $config | jq -r '.standard_build.enabled')
          repo_enabled=$(echo $config | jq -r '.repo_build.enabled')
          base_names_standard=$(echo $config | jq -r '.standard_build.base_os.base_name | join(",")')
          base_versions_standard=$(echo $config | jq -r '.standard_build.base_os.base_version | join(",")')
          base_repo_standard=$(echo $config | jq -r '.standard_build.base_repo')
          echo "standard_enabled=$standard_enabled" >> $GITHUB_OUTPUT
          echo "repo_enabled=$repo_enabled" >> $GITHUB_OUTPUT
          echo "base_names_standard=$base_names_standard" >> $GITHUB_OUTPUT
          echo "base_versions_standard=$base_versions_standard" >> $GITHUB_OUTPUT
          echo "base_repo_standard=$base_repo_standard" >> $GITHUB_OUTPUT

      - name: Set default values if build-config.json is missing
        id: set-defaults
        if: steps.check-jsonfile.outputs.config_exists == 'false'
        run: |
          echo "standard_enabled=true" >> $GITHUB_OUTPUT
          echo "repo_enabled=true" >> $GITHUB_OUTPUT

          echo "base_names_standard=el9" >> $GITHUB_OUTPUT
          echo "base_versions_standard=23" >> $GITHUB_OUTPUT
          echo "base_repo_standard=testing" >> $GITHUB_OUTPUT

      - name: Combine configurations
        id: combine-config
        run: |
          base_names=($(echo ${{ steps.read-config.outputs.base_names_standard || steps.set-defaults.outputs.base_names_standard }} | tr ',' ' '))
          base_versions=($(echo ${{ steps.read-config.outputs.base_versions_standard || steps.set-defaults.outputs.base_versions_standard }} | tr ',' ' '))
          combinations=()
          for base_name in "${base_names[@]}"; do
            for base_version in "${base_versions[@]}"; do
              combinations+=("{\"base_name\":\"$base_name\",\"base_version\":\"$base_version\"}")
            done
          done
          combinations_json=$(printf '%s\n' "${combinations[@]}" | jq -R . | jq -s .)
          echo "image_combinations=$combinations_json" >> $GITHUB_OUTPUT

      - name: Trigger standard build workflow
        if: steps.read-config.outputs.standard_enabled == 'true' || steps.set-defaults.outputs.standard_enabled == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            const combinations = JSON.parse(process.env.IMAGE_COMBINATIONS);
            for (const combination of combinations) {
              const result = await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'standard-build.yml',
                ref: context.ref,
                inputs: {
                  image: "${{ matrix.image }}",
                  base_name: combination.base_name,
                  base_version: combination.base_version,
                  base_repo: "${{ steps.read-config.outputs.base_repo_standard || steps.set-defaults.outputs.base_repo_standard }}"
                }
              });
              console.log(result);
            }
        env:
          IMAGE_COMBINATIONS: ${{ steps.combine-config.outputs.image_combinations }}
