name: Main Workflow

on:
  push:
    branches:
      - main
      - testing-branch
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-build]

jobs:
  check-config:
    runs-on: ubuntu-latest
    outputs:
      standard_enabled: ${{ steps.read-config.outputs.standard_enabled }}
      repo_enabled: ${{ steps.read-config.outputs.repo_enabled }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for build-config.json
        id: check-json
        run: |
          if [ ! -f "build-config.json" ]; then
            echo "build-config.json not found"
            echo "standard_enabled=false" >> $GITHUB_OUTPUT
            echo "repo_enabled=false" >> $GITHUB_OUTPUT
          else
            echo "build-config.json found"
          fi

      - name: Read build-config.json
        id: read-config
        if: steps.check-json.outputs.standard_enabled != 'false' || steps.check-json.outputs.repo_enabled != 'false'
        run: |
          config=$(cat build-config.json)
          standard_enabled=$(echo $config | jq -r '.standard_build.enabled')
          repo_enabled=$(echo $config | jq -r '.repo_build.enabled')
          echo "standard_enabled=$standard_enabled" >> $GITHUB_OUTPUT
          echo "repo_enabled=$repo_enabled" >> $GITHUB_OUTPUT

      - name: Trigger standard build workflow
        if: ${{ needs.check-config.outputs.standard_enabled == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'standard-build.yml',
              ref: context.ref
            })

      - name: Trigger repo build workflow
        if: ${{ needs.check-config.outputs.repo_enabled == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'repo-build.yml',
              ref: context.ref
            })

      - name: Trigger both build workflows
        if: ${{ needs.check-config.outputs.standard_enabled == 'true' && needs.check-config.outputs.repo_enabled == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'standard-build.yml',
              ref: context.ref
            })
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'repo-build.yml',
              ref: context.ref
            })