name: Standard Build

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'
        required: true
      base_name:
        description: 'Base OS name'
        required: true
      base_version:
        description: 'Base OS version'
        required: true
      base_repo:
        description: 'Base repository'
        required: true

jobs:
  build-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: make date tag
        id: mkdatetag
        run: echo "dtag=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

      - name: Check for build-config.json in ${{ github.event.inputs.image }}
        id: check-jsonfile
        run: |
          if [ ! -f "${{ github.event.inputs.image }}/build-config.json" ]; then
            echo "No build-config.json found in ${{ github.event.inputs.image }}."
            exit 1
          else
            echo "build-config.json exists in ${{ github.event.inputs.image }}"
          fi

      - name: Build ${{ github.event.inputs.image }}:${{ github.event.inputs.base_name }}-${{ github.event.inputs.base_repo }}
        uses: opensciencegrid/build-container-action@v0.6.0
        with:
          osg_series: ${{ github.event.inputs.base_version }}
          osg_repo: ${{ github.event.inputs.base_repo }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
        env:
          BASE_NAME: ${{ github.event.inputs.base_name }}
          BASE_VERSION: ${{ github.event.inputs.base_version }}
          BASE_REPO: ${{ github.event.inputs.base_repo }}

      - name: Push to Harbor (${{ github.event.inputs.base_version }}-development)
        if: github.event.inputs.base_version != '23'
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ github.event.inputs.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Harbor (${{ github.event.inputs.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: hub.opensciencegrid.org
          registry_user: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          registry_pass: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Push to Docker Hub (${{ github.event.inputs.base_version }}-development)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: development
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ github.event.inputs.base_version }}-testing)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: testing
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub (${{ github.event.inputs.base_version }}-release)
        if: always()
        uses: opensciencegrid/push-container-action@main
        with:
          repo: release
          osg_series: ${{ github.event.inputs.base_version }}
          context: ${{ github.event.inputs.image }}
          base_os: ${{ github.event.inputs.base_name }}
          registry_url: docker.io
          registry_user: ${{ secrets.DOCKER_USERNAME }}
          registry_pass: ${{ secrets.DOCKER_PASSWORD }}
